blank_issues_enabled: false
contact_links:
  - name: Support Forum
    url: https://wordpress.org/support/plugin/wordpress-popular-posts/
    about: If you need technical assistance with WP Popular Posts or have other questions the best place to ask is on the support forum
